// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {license} from '../models';
import {db} from '../models';

export function ActivateLicense(arg1:string):Promise<license.Status>;

export function AppVersion():Promise<string>;

export function CheckForUpdates():Promise<void>;

export function DeactivateLicense():Promise<void>;

export function DeleteImport(arg1:number):Promise<boolean>;

export function GetBorderCrossings(arg1:string):Promise<Array<db.BorderCrossing>>;

export function GetDailyRecords(arg1:string):Promise<Array<db.DailyRecord>>;

export function GetDriverProfile(arg1:string):Promise<db.DriverProfile>;

export function GetDriverVehicles(arg1:string):Promise<Array<db.DriverVehicle>>;

export function GetEventsAndFaults(arg1:string):Promise<Array<db.CardEvent>>;

export function GetGnssPoints(arg1:string):Promise<Array<db.GnssPoint>>;

export function GetLoadTypeEntries(arg1:string):Promise<Array<db.LoadTypeEntry>>;

export function GetLoadUnloadOps(arg1:string):Promise<Array<db.LoadUnloadOp>>;

export function GetPlaceRecords(arg1:string):Promise<Array<db.PlaceRecord>>;

export function ImportDDDFromBytes(arg1:string,arg2:string):Promise<db.ImportResult>;

export function ImportDDDFromPath(arg1:string):Promise<db.ImportResult>;

export function LicenseStatus():Promise<license.Status>;

export function ListDrivers():Promise<Array<db.DriverSummary>>;

export function ListImports(arg1:string):Promise<Array<db.ImportInfo>>;

export function PendingFileOpens():Promise<Array<string>>;

export function PrintWindow():Promise<void>;

export function WipeDatabase():Promise<db.WipeStats>;
