// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function DeactivateLicense() {
  return window['go']['main']['App']['DeactivateLicense']();
}

export function DeleteImport(arg1) {
  return window['go']['main']['App']['DeleteImport'](arg1);
}

export function GetDailyRecords(arg1) {
  return window['go']['main']['App']['GetDailyRecords'](arg1);
}

export function GetDriverProfile(arg1) {
  return window['go']['main']['App']['GetDriverProfile'](arg1);
}

export function GetDriverVehicles(arg1) {
  return window['go']['main']['App']['GetDriverVehicles'](arg1);
}

export function GetEventsAndFaults(arg1) {
  return window['go']['main']['App']['GetEventsAndFaults'](arg1);
}

export function GetGnssPoints(arg1) {
  return window['go']['main']['App']['GetGnssPoints'](arg1);
}

export function GetPlaceRecords(arg1) {
  return window['go']['main']['App']['GetPlaceRecords'](arg1);
}

export function ImportDDDFromBytes(arg1, arg2) {
  return window['go']['main']['App']['ImportDDDFromBytes'](arg1, arg2);
}

export function ImportDDDFromPath(arg1) {
  return window['go']['main']['App']['ImportDDDFromPath'](arg1);
}

export function LicenseStatus() {
  return window['go']['main']['App']['LicenseStatus']();
}

export function ListDrivers() {
  return window['go']['main']['App']['ListDrivers']();
}

export function ListImports(arg1) {
  return window['go']['main']['App']['ListImports'](arg1);
}

export function PendingFileOpens() {
  return window['go']['main']['App']['PendingFileOpens']();
}

export function PrintWindow() {
  return window['go']['main']['App']['PrintWindow']();
}

export function WipeDatabase() {
  return window['go']['main']['App']['WipeDatabase']();
}
