// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenAndParseDDD() {
  return window['go']['main']['App']['OpenAndParseDDD']();
}

export function ParseDDDBytes(arg1, arg2, arg3) {
  return window['go']['main']['App']['ParseDDDBytes'](arg1, arg2, arg3);
}

export function ParseDDDFromPath(arg1) {
  return window['go']['main']['App']['ParseDDDFromPath'](arg1);
}

export function PrintWindow() {
  return window['go']['main']['App']['PrintWindow']();
}
