// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteImport(arg1) {
  return window['go']['main']['App']['DeleteImport'](arg1);
}

export function GetDailyRecords(arg1) {
  return window['go']['main']['App']['GetDailyRecords'](arg1);
}

export function GetDriverProfile(arg1) {
  return window['go']['main']['App']['GetDriverProfile'](arg1);
}

export function GetDriverVehicles(arg1) {
  return window['go']['main']['App']['GetDriverVehicles'](arg1);
}

export function GetEventsAndFaults(arg1) {
  return window['go']['main']['App']['GetEventsAndFaults'](arg1);
}

export function GetGnssPoints(arg1) {
  return window['go']['main']['App']['GetGnssPoints'](arg1);
}

export function GetPlaceRecords(arg1) {
  return window['go']['main']['App']['GetPlaceRecords'](arg1);
}

export function ImportDDDDialog() {
  return window['go']['main']['App']['ImportDDDDialog']();
}

export function ImportDDDFromPath(arg1) {
  return window['go']['main']['App']['ImportDDDFromPath'](arg1);
}

export function ListDrivers() {
  return window['go']['main']['App']['ListDrivers']();
}

export function ListImports(arg1) {
  return window['go']['main']['App']['ListImports'](arg1);
}

export function PrintWindow() {
  return window['go']['main']['App']['PrintWindow']();
}

export function WipeDatabase() {
  return window['go']['main']['App']['WipeDatabase']();
}
