// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenAndParseDDD():Promise<main.ParseResult>;

export function ParseDDDBytes(arg1:string,arg2:Array<number>,arg3:boolean):Promise<main.ParseResult>;

export function ParseDDDFromPath(arg1:string):Promise<main.ParseResult>;

export function PrintWindow():Promise<void>;
