// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function DeleteImport(arg1:number):Promise<boolean>;

export function GetDailyRecords(arg1:string):Promise<Array<db.DailyRecord>>;

export function GetDriverProfile(arg1:string):Promise<db.DriverProfile>;

export function GetDriverVehicles(arg1:string):Promise<Array<db.DriverVehicle>>;

export function GetEventsAndFaults(arg1:string):Promise<Array<db.CardEvent>>;

export function GetGnssPoints(arg1:string):Promise<Array<db.GnssPoint>>;

export function GetPlaceRecords(arg1:string):Promise<Array<db.PlaceRecord>>;

export function ImportDDDDialog():Promise<db.ImportResult>;

export function ImportDDDFromPath(arg1:string):Promise<db.ImportResult>;

export function ListDrivers():Promise<Array<db.DriverSummary>>;

export function ListImports(arg1:string):Promise<Array<db.ImportInfo>>;

export function PrintWindow():Promise<void>;

export function WipeDatabase():Promise<db.WipeStats>;
